name: simple

on: workflow_dispatch

jobs:
  build:

    runs-on: ubuntu-latest
    timeout-minutes: 9999

    steps:
    - name: Download Ngrok
      run: |
        wget https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip
        unzip ngrok-stable-linux-amd64.zip
    - name: Connect your NGROK account
      run: ./ngrok authtoken $NGROK_AUTH_TOKEN
      env:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
    - name: Download Important Files.
      run: |
        wget https://raw.githubusercontent.com/simplehacker01/Win10/main/NGROK-AP.bat
        wget https://raw.githubusercontent.com/simplehacker01/Win10/main/NGROK-CHECK.bat
        wget https://raw.githubusercontent.com/simplehacker01/Win10/main/loop.bat
    - name: Make YML file for NGROK.
      run: ./NGROK-AP.bat
    - name: Enable RDP Access.
      run: |
        sudo ufw allow 3389/tcp
        sudo sed -i 's/PasswordAuthentication no/PasswordAuthentication yes/' /etc/ssh/sshd_config
        sudo service ssh restart
    - name: Create Tunnel
      run: ./ngrok start --all
    - name: Connect to your RDP 2core-7GB Ram.
      run: ./NGROK-CHECK.bat
    - name: All Done! You can close the terminal now! Maximum VM time: 6h.
      run: ./loop.bat
